### ISSUE TITLE
API 14 support

### ISSUE THREAD

**Issue by rainman20** [openkwaky/ratingreminder#4]
Hi there, 
Is it possible to add sdk version 14 support?
the library min version is 16 and can't be used on apps which support 14
thanks

**Comment by openkwaky** [comment]
Hello Rainman20,

Thank you for your request :)
I check today if it is required and I change it.
I'll inform you when it is available

**Comment by openkwaky** [comment]
The min version is now 10.
Can you check in your project ?
The new release is 1.8
